##  This sample Rakefile will copy a file to the /Users/Shared directory
##
##  To build a package, change to the directory containing this Rakefile and
##  run the command "rake pkg". You will need sudo access to build the pkg.
##  To build a dmg file, run the "rake dmg" command.

require 'pathname'
require 'fileutils'
require "#{Pathname.pwd.parent}/cart"

task :default => :pkg

# Any variables that need to be changed should be done inside the customize
# method
def customize
  @title = "Install_Firefox"
  @reverse_domain = "com.puppetlabs"
end

# The pack method is for adding files to the package's payload. Note that
# @working_tree['WORK_D'] is the path to the working directory. All files
# installed into this directory will be copied into the package's payload.
def pack
  FileUtils.mkdir_p("#{@working_tree['WORK_D']}/Users/Shared")
  safe_system("#{INSTALL} -m 755 special.file #{@working_tree['WORK_D']}/Users/Shared/special.file")
end


### Nothing Below this line should need to be modified ###


desc "This task will create an Apple .pkg file"
task :pkg do
  customize
  make_directory_tree
  pack
  output_file
  build_package
  copy_to_local_dir(@package_file)
end

desc "This task will create an Apple .pkg encapsulated into a .dmg file"
task :dmg do
  customize
  make_directory_tree
  pack
  output_file
  build_dmg
desc "This task will create a .zip file with your package in it."
task :zip do
  customize
  make_directory_tree
  pack
  output_file
  build_zip
  announce("Your package #{@zip_file} has been built!")
end
